# fly.toml app configuration file generated for full-stack-open-pokedex-patient-bird-399 on 2024-12-19T12:53:59+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
[env]
  PORT = "3000"

[processes]
  app = "node app.js"
  primary_region = 'mad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  strategy = 'canary'