name: Deploy Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Instalar dependencias
        run: npm install

      - name: Construir aplicación
        run: npm run build

      - run: flyctl deploy --remote-only -a ${{ secrets.FLY_APP_NAME }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
            url: https://${{ secrets.FLY_APP_NAME }}.fly.dev/health
            max-attempts: 3
            retry-delay: 5s
            follow-redirect: true