name: Deploy Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Instalar dependencias
        if: ${{ github.event_name == 'push' }}
        run: npm install

      - name: Construir aplicación
        if: ${{ github.event_name == 'push' }}
        run: npm run build

      - name: Deploy app
        if: ${{ github.event_name == 'push' }}
        run: flyctl deploy --remote-only -a ${{ secrets.FLY_APP_NAME }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Check the deployed service URL
        if: ${{ github.event_name == 'push' }}
        uses: jtalk/url-health-check-action@v4
        with:
            url: https://${{ secrets.FLY_APP_NAME }}.fly.dev/health
            max-attempts: 3
            retry-delay: 5s
            follow-redirect: true

  tag_release:
    needs: [deploy]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' }}
        uses: anothrNick/github-tag-action@1.71.0
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            WITH_V: true
            DEFAULT_BUMP: patch